name: tmate-ssh-server
on:
  workflow_dispatch:
jobs:
  tmate-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start tmate session
        uses: tmate-io/tmate-action@v2.0.2
        with:
          limit-access-to-actor: true
